---
title: "About"
---

My name is Noah and I'm a data scientist and engineer. I have worked as a CNC programmer/operator, a draftsman/technical designer, a security guard, and a guitar repair/salesman. I was a self-taught hobbyist Python developer for years before being made aware that this was a marketable skill and changing careers in my 30s.

More recently I have worked for [Galvanize, Inc](https://www.galvanize.com/), [CMS AI Health Outcomes Challenge](https://www.cms.gov/newsroom/press-releases/cms-selects-winner-and-runner-artificial-intelligence-health-outcomes-challenge) winning startup [ClosedLoop.ai](https://www.closedloop.ai/), and [top-ranking](https://www.cms.gov/newsroom/press-releases/cms-selects-winner-and-runner-artificial-intelligence-health-outcomes-challenge) ACO REACH [ilumed](https://ilumed.com).

Today I work freelance as a contract data engineer, scientist, analyist & Python developer, as well as private tutor and coach focusing on python, the UNIX command line, bash, and vim.


If you are interested in working with me, please don't hesitate to reach out.

    email:      n@sweep.sh
    phone:      234.249.1314
    li:         in/noah-shreve

